title: Tech Engineer 3D
url:
baseurl: /portfolio
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: Jekyll template with example content for a web agency.

# Author details for the jekyll-seo-tag gem
author:
  name:
  email:
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Urban Template
  links:
    - https://github.com/CloudCannon/urban-jekyll-template

timezone: Etc/UTC

collections:
  staff_members:
    output: false
  clients:
    output: true
  graphics:
    output: true
  galleries:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  posts:
    enabled: ["categories"]
    permalinks:
      categories: "/blog/:type/:name/"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "graphics"
    values:
      layout: "graphic"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "galleries"
    values:
      layout: "gallery"
      _options:
        image_path:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "images"
    values:
      image: true

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
  - Github

  # ------------
  # Site Options

  # Lazy loading images
#   If you enable lazy loading, all images will add the loading="lazy" attribute.
#   This will make your site load faster, but it may not be supported in all browsers.
#   You can also set loading="" to other values for specific images to override the default behavior.
#   Options: "auto", "eager", "lazy"
#   See https://web.dev/browser-level-image-lazy-loading/ for more information.
lazy_loading_images: true # enables lazy loading of images (recommended)
enable_darkmode: true # enables switching between light/dark modes
enable_masonry: true # enables automatic project cards arrangement
